name: CI/CD Pipeline for Windows Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build the frontend
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: |
            dist

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact from build
        uses: actions/download-artifact@v2
        with:
          name: production-files

      - name: Deploy using PowerShell
        run: |
          $password = ConvertTo-SecureString ${{ secrets.SERVER_PASSWORD }} -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential ( ${{ secrets.SERVER_USER }}, $password)
          Invoke-Command -ComputerName ${{ secrets.SERVER_IP }} -Credential $cred -ScriptBlock {
            Copy-Item -Path "C:\path\to\local\dist\*" -Destination "C:\path\to\server\directory" -Recurse
            Restart-Service -Name "YourAppService"
          }
        shell: pwsh
